### ISSUE TITLE
Firefox 52.0.1 x32, can't save settings in PlayThis 0.2.1.0 popup

### ISSUE THREAD

**Issue by Cris--** [anxdpanic/PlayThis-Extension#4]
It works for month very good but now settings are empty and i can't save new settings.

in my Firefox profil directory there is a "browser-extension-data\playthis@anxdpanic" with an empty storage.js (only {} ) inside.

Please how can i add my Kodi IP/Port?

Hope this project is not dead! ^^

**Comment by Milliw** [comment]
Same here on FF 52.0 32bit

**Comment by anxdpanic** [comment]
Sorry for the delays, this will be fixed. I should hopefully be able to get this resolved in the near future pending available time.

**Comment by Cris--** [comment]
Ok, Mozilla fault. After updating to FF 53.0 x32 i can save the ip and it works now!

**Comment by anxdpanic** [comment]
Thanks for the heads up, web extensions are still relatively new and being worked on for FF. Was likely a regression introduced in 52.0.
