### ISSUE TITLE
Trying get it to work

### ISSUE THREAD

**Issue by STHellRaiser** [anxdpanic/PlayThis-Extension#5]
I am bit a baffled at how you get it to work as far as am aware have everything set up correctly on kodi and on chrome and config correctly. but every time i click send to playthis nothing happens. with and without playthis being open on kodi. could you please explain were am going wrong on this?

Regards

**Comment by anxdpanic** [comment]
Will need more details to help, first thing is ensure your port in the extension is 9090 unless you've configured it in Kodi's advancedsettings.xml. And that Kodi setting: Settings -> Services -> Control -> Allow remote control by programs on other systems, is enabled.

If those are set and still not working, if you can post a link to the kodi.log of you trying with Debug logging, and component-specific logging for JSON-RPC requests enabled then we can take a look to see if there is any indication of Kodi receiving the request from the extension.

**Comment by anxdpanic** [comment]
Closing, inactivity
