### ISSUE TITLE
No connection to OSMC

### ISSUE THREAD

**Issue by mkskarch** [anxdpanic/PlayThis-Extension#6]
Hi, i have a RPi with OSMC installed. OSMC is the newest version with Kodi 17.3 installed. I've got the PlayThis Add-on installed in Kodi. I can write in stream URLs and it does play, all fine. Unfortunately I can't get the PlayThis Firefox plugin connected to the RPi. "Control via http" is enabled, the plugin is configured wit correct IP address of the RPi and the same port number as defined in Kodi. Any ideas? 

PS: tried with Firefox 54.0.1

**Comment by anxdpanic** [comment]
Settings -> Services -> Remote Control -> Allow remote control by programs on other systems 
is the setting required, it's done over websockets and port 9090 (changing this port requires a change in advancedsettings.xml).

**Comment by mkskarch** [comment]
Thank you for the very quick reply! "Allow remote control by programs on other systems" is enabled, however the port number is set to 80 and it is not possible to change it to 9090 (turns automatically back to 80 with error "fails to start.").
Where is this advancedsettings.xml in PlayThis, so I can change default portnumber 9090 to 80?

**Comment by anxdpanic** [comment]
The port number in Kodi for HTTP will not change to 9090. The default for json-rpc websockets is 9090 (and you can't change that directly in Kodi), you should be able to set the PlayThis extension port(in browser) to 9090(default) as long as "Allow remote control by programs on other systems" is enabled.

The advancedsettings.xml is for Kodi not PlayThis, on OSMC it is in ~/.kodi/userdata/advancedsettings.xml (has to be created, doesn't exist by default.) The setting to changed the port and more information can be found: http://kodi.wiki/view/Advancedsettings.xml 
Section 2.1.2 jsonrpc is the relevant section to our conversation.

**Comment by mkskarch** [comment]
Oh, no! That was that easy! I simply shouldn't have changed the default port number 9090 in the Firefox extension! Now that works, all fine! Thanks a lot!

**Comment by anxdpanic** [comment]
Great to hear 👍
