### ISSUE TITLE
Facebook videos have no sound

### ISSUE THREAD

**Issue by bendy101** [anxdpanic/PlayThis-Extension#7]
the audio is not being passed to kodi for facebook videos

tested link (is public so you can test it)
https://www.facebook.com/bendy303/videos/vb.509742320/10154750613447321/

other chrome extensions work:
PLay To Kodi
SendtoKodi
KodiBuddy
KassiShare

**Comment by anxdpanic** [comment]
This should be fixed with https://github.com/anxdpanic/plugin.video.playthis/commit/8a930e4ad270b8b5c16c9c35be01011fe2941b2e
PlayThis add-on 3.4.4 with the fix is now updated on my repo. 
Please re-open with debug log if having any further issues with Facebook videos.
